from __future__ import annotations

import os
import sqlite3
from pathlib import Path
from typing import Any

from dotenv import load_dotenv

try:
    from psycopg import connect
    from psycopg.rows import dict_row
except ImportError:  # pragma: no cover - local sqlite fallback without postgres deps
    connect = None
    dict_row = None

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent
SQLITE_DB_PATH = Path(os.getenv("AVIVA_DB_PATH", BASE_DIR / "aviva.sqlite3"))
POSTGRES_URL = (
    os.getenv("SUPABASE_DB_URL")
    or os.getenv("DATABASE_URL")
    or os.getenv("POSTGRES_URL")
    or os.getenv("POSTGRES_URL_NON_POOLING")
)


def using_postgres() -> bool:
    return bool(POSTGRES_URL)


def _normalize_query(query: str) -> str:
    if using_postgres():
        return query.replace("?", "%s")
    return query


def get_connection():
    if using_postgres():
        if connect is None:
            raise RuntimeError("Instale psycopg[binary] para usar Supabase/Postgres.")
        return connect(POSTGRES_URL, row_factory=dict_row)

    connection = sqlite3.connect(SQLITE_DB_PATH)
    connection.row_factory = sqlite3.Row
    return connection


def fetch_one(query: str, params: tuple[Any, ...] = ()):
    with get_connection() as connection:
        cursor = connection.execute(_normalize_query(query), params)
        return cursor.fetchone()


def fetch_all(query: str, params: tuple[Any, ...] = ()) -> list[Any]:
    with get_connection() as connection:
        cursor = connection.execute(_normalize_query(query), params)
        return cursor.fetchall()


def execute(query: str, params: tuple[Any, ...] = ()) -> int:
    normalized_query = _normalize_query(query)
    with get_connection() as connection:
        if using_postgres() and normalized_query.lstrip().upper().startswith("INSERT"):
            cursor = connection.execute(f"{normalized_query} RETURNING id", params)
            row = cursor.fetchone()
            connection.commit()
            return int(row["id"])

        cursor = connection.execute(normalized_query, params)
        connection.commit()
        return int(getattr(cursor, "lastrowid", 0) or 0)


def _schema_statements(schema: str) -> list[str]:
    return [statement.strip() for statement in schema.split(";") if statement.strip()]


def initialize_database() -> None:
    if using_postgres():
        schema = """
        CREATE TABLE IF NOT EXISTS users (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name TEXT NOT NULL,
          email TEXT NOT NULL UNIQUE,
          password_hash TEXT NOT NULL,
          role TEXT NOT NULL CHECK(role IN ('member', 'admin')),
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        );

        CREATE TABLE IF NOT EXISTS events (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          title TEXT NOT NULL,
          description TEXT NOT NULL,
          date DATE NOT NULL,
          start_time TIME NOT NULL,
          end_time TIME NOT NULL,
          location TEXT NOT NULL,
          image_url TEXT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        );
        """
    else:
        schema = """
        CREATE TABLE IF NOT EXISTS users (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          name TEXT NOT NULL,
          email TEXT NOT NULL UNIQUE,
          password_hash TEXT NOT NULL,
          role TEXT NOT NULL CHECK(role IN ('member', 'admin')),
          created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );

        CREATE TABLE IF NOT EXISTS events (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          title TEXT NOT NULL,
          description TEXT NOT NULL,
          date TEXT NOT NULL,
          start_time TEXT NOT NULL,
          end_time TEXT NOT NULL,
          location TEXT NOT NULL,
          image_url TEXT,
          created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
          updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
        """

    with get_connection() as connection:
        if using_postgres():
            with connection.cursor() as cursor:
                for statement in _schema_statements(schema):
                    cursor.execute(statement)
        else:
            connection.executescript(schema)
        connection.commit()
